inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "gemfiles/*"
    - "vendor/**/*"
    - "test/dummy/db/schema.rb"

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
